name: Build STM32 Projects
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  
        uses: actions/checkout@v3

      - name: Build Sampling
        uses: xanderhendriks/action-build-stm32cubeide@v15.0
        with:
          project-path: 'Microcontroller/Sampling'
          project-target: 'Sampling/Debug'

      - name: Build Processing
        uses: xanderhendriks/action-build-stm32cubeide@v15.0
        with:
          project-path: 'Microcontroller/Processing'
          project-target: 'Processing/Debug'
          
